schemaVersion: 2.1.0

metadata:
  name: camel-k-dev-environment
  version: 1.0.0
  description: Devfile for a development environment with Camel K, OpenShift CLI, and Java.

components:
  - name: java-runtime
    container:
      image: registry.access.redhat.com/ubi8/openjdk-11
      memoryLimit: 8Gi
      mountSources: true
      endpoints:
        - name: http
          targetPort: 8080
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=50.0"

  - name: oc-kamel-tools
    container:
      image: registry.access.redhat.com/openshift4/ose-cli:latest
      memoryLimit: 4Gi
      mountSources: true
      command:
        - /bin/sh
        - -c
        - |
          curl -L https://github.com/apache/camel-k/releases/download/v1.7.0/camel-k-client-1.7.0-linux-64bit.tar.gz -o camel-k.tar.gz && \
          tar -xzf camel-k.tar.gz -C /usr/local/bin/ && rm camel-k.tar.gz && \
          echo 'Camel K and OpenShift CLI installed'

  - name: maven
    container:
      image: quay.io/eclipse/che-java8-maven:nightly
      memoryLimit: 512Mi
      mountSources: true

  - name: java-vscode
    container:
      image: quay.io/eclipse/che-plugin-java:nightly
      memoryLimit: 4Gi
      mountSources: true

commands:
  - id: run-java-app
    exec:
      component: java-runtime
      commandLine: "java -jar /path/to/your/app.jar"
      group:
        kind: run
        isDefault: true

  - id: kamel-run
    exec:
      component: oc-kamel-tools
      commandLine: "kamel run /projects/CamelKRoute.java"
      group:
        kind: run
        isDefault: false

  - id: oc-login
    exec:
      component: oc-kamel-tools
      commandLine: "oc login --token=<your-token> --server=<your-server>"
      group:
        kind: build
        isDefault: true
