apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: postgres-debezium-connector
  namespace: integration-project-2
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    plugin.name: pgoutput
    database.hostname: integration.integration-project-2.svc.cluster.local
    database.port: 5432
    database.user: integration
    database.password: averysecurepassword
    database.dbname: postgres
    table.include.list: public.people, public.addresses
    topic.prefix: legacydatachanged
    slot.name: changecapture1
    publication.name: changecapture1
  tasksMax: 1