apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kafka-operator-subscription
  namespace: integration-project-2
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace